# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений без токена (10 в минуту)
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# получение объявлений с токеном (20 в минуту).
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 40aa1dc45d0b456a3f0f79491d85811c02d18566 # Токен admin

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b60c5784f5d38732e8968fc2360162ecbd3ef098 # Токен ivanov

{
  "title": "Стул деревянный",
  "description": "не срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token b60c5784f5d38732e8968fc2360162ecbd3ef098 # токен ivanov

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# Фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2026-03-01
Content-Type: application/json

###

# Удаление объявления создателем.
DELETE {{baseUrl}}/advertisements/4/
Authorization: Token 40aa1dc45d0b456a3f0f79491d85811c02d18566 # Токен admin
